services:
  # NEXON services
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: didiskywalker/nexon-frontend
    container_name: nexon_frontend
    ports:
      - 3000:80
    networks:
      - internal

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: didiskywalker/nexon-backend
    container_name: nexon_backend
    ports:
      - 8000:80
    networks:
      - internal
      - mlflow
    environment:
      - NEXON_MONGO_HOST=${NEXON_MONGO_HOST}
      - NEXON_MONGO_PORT=${NEXON_MONGO_PORT}
      - NEXON_MONGO_USER=${NEXON_MONGO_USER}
      - NEXON_MONGO_PASS=${NEXON_MONGO_PASS}
      - NEXON_MONGO_DB=${NEXON_MONGO_DB}
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-server:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
    volumes:
      # - mlflow_data:/artifacts
      - ./app/api:/app/api
      - ./app/controller:/app/controller
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: nexon_db
    ports:
      - 27017:27017
    networks:
      - internal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${NEXON_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${NEXON_MONGO_PASS}
      - MONGO_INITDB_DATABASE=${NEXON_MONGO_DB}

networks:
  internal:
  mlflow:
    external: true
    name: mlflow-network

volumes:
  mlflow_data:
    external: true
